# Use the official Nginx base image
FROM nginx:latest

# Copy custom Nginx configuration
COPY ./conf/nginx.conf /etc/nginx/nginx.conf

# Copy HTML content
COPY ./html /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
