### Use an official OpenJDK runtime as a parent image/ Warning: OpenJDK is deprecated
### Switching to eclipse-temurin
FROM eclipse-temurin:21

### Set the working directory
WORKDIR /app

### Copy the JAR file into the container
COPY helloworld.jar app.jar
COPY visitorpattern.jar app2.jar

### Command to run the JAR file
# ENTRYPOINT ["java", "-jar", "app2.jar"]
CMD ["java", "-jar", "app.jar"]